// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc620.ElderKevin1_1.commands;

import org.usfirst.frc620.ElderKevin1_1.Robot;
import org.usfirst.frc620.ElderKevin1_1.RobotMap;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class ActuateForklift extends Command {
	private Joystick stick;
    private boolean bottomExtended, topExtended;
    private Timer timer = new Timer();
    private double turnOffBottom = -1.0;
    private double turnOffTop = -1.0;
    private final double TURN_OFF_TIMEOUT = 1.0;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public ActuateForklift() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.forklift);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.forklift.retractBottom();
        Robot.forklift.retractTop();
        stick = Robot.oi.joystick;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if(rTriggerIsPressed() && !bottomExtended) {
            Robot.forklift.extendBottom();
            bottomExtended = true;
            turnOffBottom = -1.0;
        } else if (!rTriggerIsPressed() && bottomExtended) {
             Robot.forklift.retractBottom();
             bottomExtended = false;
             turnOffBottom = timer.get() + TURN_OFF_TIMEOUT;
        } else if (!rTriggerIsPressed() && (timer.get() > turnOffBottom)) {
        	Robot.forklift.turnOffBottom();
        }

        if(lTriggerIsPressed() && !topExtended) {
            Robot.forklift.extendTop();
            topExtended = true;
            turnOffTop = -1.0;
        } else if(!lTriggerIsPressed() && topExtended) {
            Robot.forklift.retractTop();
            topExtended = false;
            turnOffTop = timer.get() + TURN_OFF_TIMEOUT;
        } else if (!lTriggerIsPressed() && (timer.get() > turnOffTop)) {
        	Robot.forklift.turnOffTop();
        }


    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }

    private boolean rTriggerIsPressed() {
        return stick.getRawAxis(2) > 0.7;
    }

    private boolean lTriggerIsPressed() {
        return stick.getRawAxis(3) > 0.7;
    }
}
